Traceback (most recent call last):
  File "/home/verif/verif-post-process/src/accum_error_alldays.py", line 654, in <module>
    main(sys.argv)
  File "/home/verif/verif-post-process/src/accum_error_alldays.py", line 641, in main
    plot(station, var, yaxis_labels[var_i], station_names[stations_i],obs,fcst,int(day),index_start)
  File "/home/verif/verif-post-process/src/accum_error_alldays.py", line 476, in plot
    if check_data_exists(filepath, station, variable) == False:
NameError: name 'check_data_exists' is not defined
MM5
MM5
MM5
MM5G
MM5G
MM5G
MM5G
WRF3GEM
WRF3GEM
WRF3GEM
WRF3NAM
WRF3NAM
WRF3NAM
WRF3GFS
WRF3GFS
WRF3GFS
WRF3GFS
WRF3NAVGEM
WRF3NAVGEM
WRF3NAVGEM
WRF3GFSgc01
WRF3GFSgc01
WRF3ARPEGE
WRF3ARPEGE
WRF4ICON
WRF4ICON
WRF4NAM
WRF4NAM
WRF4NAM
NMM3NAM
NMM3NAM
NMM3NAM
NMM3GFS
NMM3GFS
WRF2NAM
WRF2NAM
WRF2NAM
WRF2NAM81
WRF2NAM81
WRF2NAM81
WRF2GFS
WRF2GFS
WRF2GFS
WRF2GFS81
WRF2GFS81
WRF2GFS81
WRF4RDPS
WRF4RDPS
WRF4RDPS
MPAS25
MPAS25
ENS
ENS_lr
ENS_hr
ENS_LR
